### ISSUE TITLE
laravel exception after restore token

### ISSUE THREAD

**Issue by KinG-InFeT** [tmarois/laravel-ads-sdk#41]
```
PHP Fatal error:  Uncaught ErrorException: fopen(php://stderr): failed to open stream: operation failed in /home/user/workspace/project/vendor/symfony/console/Output/ConsoleOutput.php:164
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/user/workspace/project/vendor/symfony/console/Output/ConsoleOutput.php(164): fopen()
#2 /home/user/workspace/project/vendor/symfony/console/Output/ConsoleOutput.php(46): Symfony\Component\Console\Output\ConsoleOutput->openErrorStream()
#3 /home/user/workspace/project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Symfony\Component\Console\Output\ConsoleOutput->__construct()
#4 /home/user/workspace/project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(98): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#5 [internal function]: Illuminate\Foundation\Bootstrap\HandleExcept in /home/user/workspace/project/vendor/symfony/console/Output/ConsoleOutput.php on line 164
PHP Fatal error:  Uncaught ErrorException: include(/home/user/workspace/project/vendor/symfony/debug/Exception/FatalErrorException.php): failed to open stream: Too many open files in /home/user/workspace/project/vendor/composer/ClassLoader.php:478
Stack trace:
#0 /home/user/workspace/project/vendor/composer/ClassLoader.php(478): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/user/workspace/project/vendor/composer/ClassLoader.php(478): include()
#2 /home/user/workspace/project/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/user/workspace/project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(147): spl_autoload_call()
#5 /home/user/workspace/project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\Foundation\Bootstrap\HandleEx in /home/user/workspace/project/vendor/composer/ClassLoader.php on line 478
```

use latest version laravel-ads-sdk and laravel 6

**Comment by timothymarois** [comment]
Hey, sorry for the delay. were you trying to do google or bing ads? and is this issue still happening? Ive not seen this before, doesn't exactly ping point to laravel ads sdk issue, unless I can see the code being used to do. Thanks.

**Comment by KinG-InFeT** [comment]
hi, i use into foreach for creare multiple ads (bing), when token expired out this error
